const movies = [
  {
    id: 1,
    name: "Дитя человеческое",
    link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH1N5BY0r9mzUvYpChHNOL6rMyaO4E5wNqEQ&usqp=CAU",
    duration: "1ч 49мин",
    trailerLink: "https://www.kinopoisk.ru/film/6803/",
  },
  {
    id: 2,
    name: "Брат",
    link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgQ4--1vxXZA6lBqqxJMybxCBGEsDnbWAegA&usqp=CAU",
    duration: "1ч 40мин",
    trailerLink: "https://www.kinopoisk.ru/film/41519/",
  },
  {
    id: 3,
    name: "Начало",
    link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTm7H3YQxjb474hqVUltrPQP2kdlq9kNjhrTg&usqp=CAU",
    duration: "2ч 28мин",
    trailerLink: "https://www.kinopoisk.ru/film/447301/",
  },
  {
    id: 4,
    name: "Самогонщики1",
    link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRp7_4ikngO5WCtsf_3wLa5PGJB2wXw65R1vQ&usqp=CAU",
    duration: "19мин",
    trailerLink: "https://www.kinopoisk.ru/film/43608/",
  },
  // {
  //   id: 5,
  //   name: "Дитя человеческое",
  //   link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH1N5BY0r9mzUvYpChHNOL6rMyaO4E5wNqEQ&usqp=CAU",
  //   duration: "1ч 49мин",
  //   trailerLink: "https://www.kinopoisk.ru/film/6803/",
  // },
  // {
  //   id: 6,
  //   name: "Брат",
  //   link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgQ4--1vxXZA6lBqqxJMybxCBGEsDnbWAegA&usqp=CAU",
  //   duration: "1ч 40мин",
  //   trailerLink: "https://www.kinopoisk.ru/film/41519/",
  // },
  // {
  //   id: 7,
  //   name: "Начало",
  //   link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTm7H3YQxjb474hqVUltrPQP2kdlq9kNjhrTg&usqp=CAU",
  //   duration: "2ч 28мин",
  //   trailerLink: "https://www.kinopoisk.ru/film/447301/",
  // },
  // {
  //   id: 8,
  //   name: "Самогонщики2",
  //   link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRp7_4ikngO5WCtsf_3wLa5PGJB2wXw65R1vQ&usqp=CAU",
  //   duration: "19мин",
  //   trailerLink: "https://www.kinopoisk.ru/film/43608/",
  // },
  // {
  //   id: 9,
  //   name: "Дитя человеческое",
  //   link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH1N5BY0r9mzUvYpChHNOL6rMyaO4E5wNqEQ&usqp=CAU",
  //   duration: "1ч 49мин",
  //   trailerLink: "https://www.kinopoisk.ru/film/6803/",
  // },
  // {
  //   id: 10,
  //   name: "Брат",
  //   link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgQ4--1vxXZA6lBqqxJMybxCBGEsDnbWAegA&usqp=CAU",
  //   duration: "1ч 40мин",
  //   trailerLink: "https://www.kinopoisk.ru/film/41519/",
  // },
  // {
  //   id: 11,
  //   name: "Начало",
  //   link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTm7H3YQxjb474hqVUltrPQP2kdlq9kNjhrTg&usqp=CAU",
  //   duration: "2ч 28мин",
  //   trailerLink: "https://www.kinopoisk.ru/film/447301/",
  // },
  // {
  //   id: 12,
  //   name: "Самогонщики3",
  //   link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRp7_4ikngO5WCtsf_3wLa5PGJB2wXw65R1vQ&usqp=CAU",
  //   duration: "19мин",
  //   trailerLink: "https://www.kinopoisk.ru/film/43608/",
  // },
];
  
export default movies;